# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20160114_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 14, 23, 24, 6, 271784), null=True, verbose_name='Message date'),
        ),
    ]
