# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20160114_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 14, 23, 31, 23, 439286), null=True, verbose_name='Message date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_address1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill To Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill To Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill To City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bill To Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill To Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bill To Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_postal_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Bill To Zip Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billto_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bill To State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_house_sales',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='In House Sales'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Order Source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_book_option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pre-Book Option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prebook_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_address1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ship To Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ship To Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_address_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ship To Address ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ship To City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ship To Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ship To Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ship To Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_postal_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Ship To Zip Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipto_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ship To State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='db.UserProfile'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='db.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='ordersource',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description displayed on order screen', max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ordersource',
            name='value',
            field=models.CharField(blank=True, help_text='Value attached to order', max_length=100, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='item_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='db.ProductStyle', verbose_name='Product Style'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='item_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='db.ProductItem', verbose_name='Product Item'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='productstyle',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='productstyle',
            name='style_sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style Sku'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address ID'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='db.UserProfile'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='claim_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Claim Number'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='damage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Damage'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='warrantycolor',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='warrantyimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='warrantyimage',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='File Extension'),
        ),
        migrations.AlterField(
            model_name='warrantyimage',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='warrantyimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='warrantyimage',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='db.Warranty'),
        ),
        migrations.AlterField(
            model_name='warrantystyle',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Style'),
        ),
    ]
